name: PublishPlugin

on:
  push:
    branches: [master]

  workflow_dispatch:

env:
  LUA: "lua=5.1"
  GCP_PROJECT_ID: "si26ef9dii9zscrxrecql6kl8eguw2"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: before install
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev luarocks
          sudo pip install hererocks
          sudo hererocks lua_install -r^ --${{ env.LUA }}
          export PATH=$PATH:$PWD/lua_install/bin

      - name: install
        run: |
          sudo make setup
          sudo make install

      - name: test
        run: |
          sudo make test

      - name: Get Luarocks API Key
        uses: google-github-actions/get-secretmanager-secrets@v0.2.2
        with:
          secrets: |-
            LUAROCKS_API_KEY:${{ env.GCP_PROJECT_ID }}/LUAROCKS_APIKEY

      - name: deploy
        run: |
          luarocks upload kong-plugin-template-transformer-*.rockspec --api-key=$LUAROCKS_API_KEY
